var hierarchy =
[
    [ "_3darray", "dd/de8/class__3darray.html", null ],
    [ "_4darray", "da/d6c/class__4darray.html", null ],
    [ "_5darray", "d7/dd1/class__5darray.html", null ],
    [ "_6darray", "df/d23/class__6darray.html", null ],
    [ "_7darray", "d8/d5f/class__7darray.html", null ],
    [ "adstring", "d5/dd1/classadstring.html", null ],
    [ "constant_quadratic_penalty", "df/dcc/classconstant__quadratic__penalty.html", null ],
    [ "dll_3darray", "d2/d88/classdll__3darray.html", null ],
    [ "dll_adstring", "de/df0/classdll__adstring.html", null ],
    [ "dll_imatrix", "dc/d65/classdll__imatrix.html", null ],
    [ "dll_init_3darray", "dd/de5/classdll__init__3darray.html", null ],
    [ "dll_init_bounded_number", "df/db3/classdll__init__bounded__number.html", null ],
    [ "dll_init_bounded_vector", "d1/d1a/classdll__init__bounded__vector.html", null ],
    [ "dll_init_imatrix", "de/d1d/classdll__init__imatrix.html", null ],
    [ "dll_init_int", "d3/dff/classdll__init__int.html", null ],
    [ "dll_init_matrix", "df/da8/classdll__init__matrix.html", null ],
    [ "dll_init_number", "d6/d9b/classdll__init__number.html", null ],
    [ "dll_init_vector", "dc/dc0/classdll__init__vector.html", null ],
    [ "dll_int", "d2/df9/classdll__int.html", null ],
    [ "dll_matrix", "d2/d92/classdll__matrix.html", null ],
    [ "dll_number", "de/da1/classdll__number.html", null ],
    [ "dll_random_effects_vector", "d6/dd5/classdll__random__effects__vector.html", null ],
    [ "dll_vector", "d2/d52/classdll__vector.html", null ],
    [ "equality_constraint_vector", "da/d59/classequality__constraint__vector.html", null ],
    [ "gaussian_prior", "d2/d9e/classgaussian__prior.html", null ],
    [ "imatrix", "dc/d7e/classimatrix.html", null ],
    [ "inequality_constraint_vector", "d6/df8/classinequality__constraint__vector.html", null ],
    [ "init_3darray", "d7/dec/classinit__3darray.html", null ],
    [ "init_4darray", "d7/dc5/classinit__4darray.html", null ],
    [ "init_5darray", "d3/d0e/classinit__5darray.html", null ],
    [ "init_6darray", "dd/d0f/classinit__6darray.html", null ],
    [ "init_7darray", "d7/da6/classinit__7darray.html", null ],
    [ "init_adstring", "df/dcc/classinit__adstring.html", null ],
    [ "init_bounded_3darray", "d0/d45/classinit__bounded__3darray.html", null ],
    [ "init_bounded_dev_vector", "d7/d31/classinit__bounded__dev__vector.html", null ],
    [ "init_bounded_matrix", "d3/d16/classinit__bounded__matrix.html", null ],
    [ "init_bounded_matrix_vector", "dd/d34/classinit__bounded__matrix__vector.html", null ],
    [ "init_bounded_number", "d7/db8/classinit__bounded__number.html", null ],
    [ "init_bounded_number_vector", "dc/dad/classinit__bounded__number__vector.html", null ],
    [ "init_bounded_vector", "d0/d33/classinit__bounded__vector.html", null ],
    [ "init_bounded_vector_vector", "d6/dfe/classinit__bounded__vector__vector.html", null ],
    [ "init_imatrix", "da/dfd/classinit__imatrix.html", null ],
    [ "init_int", "d4/d6d/classinit__int.html", null ],
    [ "init_ivector", "d9/d68/classinit__ivector.html", null ],
    [ "init_line_adstring", "d8/d33/classinit__line__adstring.html", null ],
    [ "init_matrix", "d3/db3/classinit__matrix.html", null ],
    [ "init_matrix_vector", "d7/d7e/classinit__matrix__vector.html", null ],
    [ "init_number", "db/d72/classinit__number.html", null ],
    [ "init_number_vector", "d1/d0f/classinit__number__vector.html", null ],
    [ "init_vector", "d6/dcf/classinit__vector.html", null ],
    [ "init_vector_vector", "de/d99/classinit__vector__vector.html", null ],
    [ "ivector", "de/d39/classivector.html", null ],
    [ "likeprof_number", "d4/dd7/classlikeprof__number.html", null ],
    [ "cstar::logisticTrait< T2 >", "db/d9a/classcstar_1_1logistic_trait.html", null ],
    [ "cstar::logisticTrait< double >", "d4/d03/classcstar_1_1logistic_trait_3_01double_01_4.html", null ],
    [ "cstar::logisticTrait< named_dvariable >", "d9/d47/classcstar_1_1logistic_trait_3_01named__dvariable_01_4.html", null ],
    [ "matrix", "d1/d8d/classmatrix.html", null ],
    [ "model_data", null, [
      [ "test_comm", "db/d6d/classtest__comm.html", null ]
    ] ],
    [ "acl::negativeLogLikelihood", "d3/d8c/classacl_1_1negative_log_likelihood.html", [
      [ "acl::multinomial", "d6/d28/classacl_1_1multinomial.html", null ],
      [ "acl::robust_multi", "df/dea/classacl_1_1robust__multi.html", null ]
    ] ],
    [ "normal_prior", "d6/da5/classnormal__prior.html", null ],
    [ "number", "d9/d28/classnumber.html", null ],
    [ "objective_function_value", "d2/d02/classobjective__function__value.html", null ],
    [ "ofstream", "d9/d93/classofstream.html", null ],
    [ "quadratic_penalty", "df/da9/classquadratic__penalty.html", null ],
    [ "quadratic_prior", "de/d8f/classquadratic__prior.html", null ],
    [ "random_effects_bounded_matrix", "da/d98/classrandom__effects__bounded__matrix.html", null ],
    [ "random_effects_bounded_vector", "d6/dcc/classrandom__effects__bounded__vector.html", null ],
    [ "random_effects_matrix", "d1/d77/classrandom__effects__matrix.html", null ],
    [ "random_effects_vector", "da/d53/classrandom__effects__vector.html", null ],
    [ "random_number_generator", "da/d50/classrandom__number__generator.html", null ],
    [ "sdreport_matrix", "d1/d1e/classsdreport__matrix.html", null ],
    [ "sdreport_number", "d2/d70/classsdreport__number.html", null ],
    [ "sdreport_vector", "d5/dae/classsdreport__vector.html", null ],
    [ "cstar::Selex< T >", "dc/d0a/classcstar_1_1_selex.html", [
      [ "cstar::LogisticCurve< T, T2 >", "de/d7b/classcstar_1_1_logistic_curve.html", null ],
      [ "cstar::LogisticCurve95< T, T2 >", "d4/d0a/classcstar_1_1_logistic_curve95.html", null ],
      [ "cstar::ParameterPerClass< T >", "d9/df4/classcstar_1_1_parameter_per_class.html", null ],
      [ "cstar::SelectivityCoefficients< T >", "de/d60/classcstar_1_1_selectivity_coefficients.html", null ]
    ] ],
    [ "SPinit_3darray", "de/d80/class_s_pinit__3darray.html", null ],
    [ "SPinit_4darray", "d3/db6/class_s_pinit__4darray.html", null ],
    [ "SPinit_bounded_3darray", "d8/d98/class_s_pinit__bounded__3darray.html", null ],
    [ "SPinit_bounded_matrix", "d2/dc7/class_s_pinit__bounded__matrix.html", null ],
    [ "SPinit_bounded_number", "da/d3b/class_s_pinit__bounded__number.html", null ],
    [ "SPinit_bounded_vector", "d4/d37/class_s_pinit__bounded__vector.html", null ],
    [ "SPinit_imatrix", "d9/d30/class_s_pinit__imatrix.html", null ],
    [ "SPinit_int", "dd/d95/class_s_pinit__int.html", null ],
    [ "SPinit_ivector", "d4/da1/class_s_pinit__ivector.html", null ],
    [ "SPinit_matrix", "d8/d77/class_s_pinit__matrix.html", null ],
    [ "SPinit_number", "d9/deb/class_s_pinit__number.html", null ],
    [ "SPinit_vector", "d2/d48/class_s_pinit__vector.html", null ],
    [ "SPint", "d5/d8a/class_s_pint.html", null ],
    [ "SPivector", "d3/dd7/class_s_pivector.html", null ],
    [ "splus_3darray", "d5/daa/classsplus__3darray.html", null ],
    [ "splus_adstring", "d2/dcb/classsplus__adstring.html", null ],
    [ "splus_imatrix", "dd/dd9/classsplus__imatrix.html", null ],
    [ "splus_init_3darray", "d1/db1/classsplus__init__3darray.html", null ],
    [ "splus_init_bounded_number", "db/d8d/classsplus__init__bounded__number.html", null ],
    [ "splus_init_bounded_vector", "d7/d2b/classsplus__init__bounded__vector.html", null ],
    [ "splus_init_matrix", "dc/db6/classsplus__init__matrix.html", null ],
    [ "splus_init_number", "de/dad/classsplus__init__number.html", null ],
    [ "splus_init_vector", "d1/d20/classsplus__init__vector.html", null ],
    [ "splus_int", "da/dc8/classsplus__int.html", null ],
    [ "splus_matrix", "d5/da2/classsplus__matrix.html", null ],
    [ "splus_number", "df/da5/classsplus__number.html", null ],
    [ "splus_vector", "d2/dfd/classsplus__vector.html", null ],
    [ "SPmatrix", "da/d04/class_s_pmatrix.html", null ],
    [ "SPnumber", "de/d12/class_s_pnumber.html", null ],
    [ "spr", "df/d47/classspr.html", null ],
    [ "SPvector", "d6/d72/class_s_pvector.html", null ],
    [ "vector", "d7/dfc/classvector.html", null ]
];