del admodel.*
del gmacs.b0*
del gmacs.p0*
del gmacs.r0*
del *.eva
del gradient.*
del gmacs.log
del gmacs.bar
del fmin.log
del mcout.rep
del gmacs.cor
del gmacs.std
del checkfile.rep
del a.a
del gmacs.rep
del ders.dat
del *.hst
del *.mc2
del *.ecm
del mcout.rep
del mcoutREC.rep
del mcoutREF.rep
del mcoutSSB.rep
del mcoutPROJ.rep
