atl::ExpressionBase< REAL_T, A > Struct Template Reference
Public Member Functions
const A & Cast () const
const REAL_T GetValue () const
const REAL_T GetValue (size_t i, size_t j=0) const
bool IsNonlinear () const
void PushIds (typename atl::StackEntry< REAL_T >::vi_storage &ids) const
void PushIds (typename atl::StackEntry< REAL_T >::vi_storage &ids, size_t i, size_t j=0) const
REAL_T EvaluateDerivative (uint32_t a) const
REAL_T EvaluateDerivative (uint32_t a, uint32_t b) const
REAL_T EvaluateDerivative (uint32_t x, uint32_t y, uint32_t z) const
REAL_T EvaluateDerivative (uint32_t a, size_t i, size_t j=0) const
REAL_T EvaluateDerivative (uint32_t a, uint32_t b, size_t i, size_t j=0) const
REAL_T EvaluateDerivative (uint32_t x, uint32_t y, uint32_t z, size_t i, size_t j=0) const
const ExpressionBase & operator= (const ExpressionBase &exp) const
size_t GetColumns () const
size_t GetRows () const
bool IsScalar () const
const A & Cast () const
const REAL_T GetValue () const
const REAL_T GetValue (size_t i, size_t j=0) const
bool IsNonlinear () const
void PushIds (typename atl::StackEntry< REAL_T >::vi_storage &ids) const
void PushIds (typename atl::StackEntry< REAL_T >::vi_storage &ids, size_t i, size_t j=0) const
REAL_T EvaluateDerivative (uint32_t x) const
REAL_T EvaluateDerivative (uint32_t x, uint32_t y) const
REAL_T EvaluateDerivative (uint32_t x, uint32_t y, uint32_t z) const
REAL_T EvaluateDerivative (uint32_t x, size_t i, size_t j=0) const
REAL_T EvaluateDerivative (uint32_t x, uint32_t y, size_t i, size_t j=0) const
REAL_T EvaluateDerivative (uint32_t x, uint32_t y, uint32_t z, size_t i, size_t j=0) const
const ExpressionBase & operator= (const ExpressionBase &exp) const
size_t GetColumns () const
size_t GetRows () const
bool IsScalar () const
std::string ToExpressionTemplateString () const
Member Function Documentation
template<class REAL_T, class A> const A& atl::ExpressionBase< REAL_T, A >::Cast () const [inline]
Cast this expression template to it's child representation.
Returns
Referenced by atl::acos(), atl::asin(), atl::atan(), atl::ceil(), atl::cos(), atl::cosh(), atl::floor(), atl::log(), atl::log10(), atl::operator*(), atl::operator+(), atl::operator-(), atl::operator/(), atl::pow(), atl::sin(), atl::sinh(), atl::sqrt(), atl::tan(), atl::tanh(), and atl::ExpressionBase< REAL_T, Add< REAL_T, LHS, RHS > >::ToExpressionTemplateString().
template<class REAL_T, class A> const A& atl::ExpressionBase< REAL_T, A >::Cast () const [inline]
Cast this expression template to it's child representation.
Returns
template<class REAL_T, class A> std::string atl::ExpressionBase< REAL_T, A >::ToExpressionTemplateString () const [inline]
Create a string representation of this expression template.
Returns
The documentation for this struct was generated from the following file:
ATL2/Expression.hpp