---
title: " A generalized size-structured assessment model for Crustaceans "
date: "`r format(Sys.time(), '%H:%M %B %d, %Y')`"
output:
  pdf_document:
    toc: true
    highlight: zenburn
    fig_caption: yes
    includes:
      in_header: mystyles.sty
    keep_tex: yes
    template: ms.tex
  html_document:
    df_print: paged
fontsize: 11pt
header-includes:
  - \usepackage{fontspec}
geometry: margin=1in
fontfamily: mathpazo
bibliography: ~/OneDrive/myref.bib
---
\pagenumbering{gobble}

```{r global_options, include=FALSE}

library(knitr)
opts_chunk$set(fig.width = 6, fig.height = 8, echo = FALSE, warning = FALSE, message = FALSE, cache=FALSE,results="asis")
clean_cache(clean = TRUE)
#include = FALSE prevents code and results from appearing in the finished file. R Markdown still runs the code in the chunk, and the results can be used by other chunks.
#echo = FALSE prevents code, but not the results from appearing in the finished file. This is a useful way to embed figures.
#message = FALSE prevents messages that are generated by code from appearing in the finished file.
#warning = FALSE prevents warnings that are generated by code from appearing in the finished.
#fig.cap = "..." adds a caption to graphical results.
#To set global options that apply to every chunk in your file, call knitr::opts_chunk$set in a code chunk. Knitr will treat each option that you pass to 
```
----


\begin{centering}
GMACS Development Team \\
  Andre Punt, James Ianelli, Steve Martell, Cody Szuwalski  
  \\
\fontfamily{cmr}
\fontsize{10}{12}
\selectfont
`r format(Sys.time(), '%B %d, %Y')` \\
\end{centering}
----

```{r child = 'Model.Rmd'}
```